//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyupovLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundLibrary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FundLibrary()
        {
            this.ReffilFund = new HashSet<ReffilFund>();
        }
    
        public int FundID { get; set; }
        public string FundName { get; set; }
        public int LibraryID { get; set; }
        public int QuanBooks { get; set; }
        public int QuanJournals { get; set; }
        public int QuanNewspapers { get; set; }
        public int QuanCollections { get; set; }
        public int QuanDissertations { get; set; }
        public int QuanReferats { get; set; }
        public string MainImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReffilFund> ReffilFund { get; set; }
        public virtual Libraries Libraries { get; set; }
    }
}
