//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyupovLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryEntities : DbContext
    {
        public LibraryEntities()
            : base("name=LibraryEntities")
        {
        }
        private static LibraryEntities _context;
        public static LibraryEntities GetContext()
        {
            if (_context == null)
            {
                _context = new LibraryEntities();
            }

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FundLibrary> FundLibrary { get; set; }
        public virtual DbSet<Libraries> Libraries { get; set; }
        public virtual DbSet<ReffilFund> ReffilFund { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<TypeLiteratures> TypeLiteratures { get; set; }
    }
}
